language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -U pip
  - pip install codecov invoke pipenv
  - inv build
script: inv test
after_success:
  - codecov
notifications:
  email: false

